import React from 'react';

const Footer = () => {
  return (
    <footer className="app-footer container">
      <div className="footer-disclaimer">
        ⚠️ <strong>Disclaimer:</strong> This information is generated by AI based on public news sources and is for informational purposes only. It is NOT financial advice. Always do your own research (DYOR) before making investment decisions.
      </div>
      <div>
        Powered by Gemini AI + Open Source News • Built for Market Intelligence
      </div>
    </footer>
  );
};

export default Footer;
